services:
  todo-db:
    image: postgres:17
    restart: always
    env_file:
      - ".env.local"
    container_name: todo-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
